spring:
  datasource:
    url: jdbc:sqlserver://unusualflowdb.database.windows.net:1433;database=unusualflowdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: unusualflowdb
    password: Test@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
